### ISSUE TITLE
SFZero plugin shouldn't use sfzero namespace

### ISSUE THREAD

**Issue by jamiebullock** [altalogix/SFZeroModule#1]
I'm putting this here as there doesn't seem to be an issue tracker for the [SFZero plugin](https://github.com/altalogix/SFZero)

I think that the plugin shouldn't use the `sfzero` namespace, which should be reserved for the SFZero module... or the module should have a different namespace like `sfzero_module`. Either way, I think they should be kept separate. Otherwise it's quite confusing glancing at the SFZero plugin code what is part of the plugin and what is the module. Personally, I think it's overkill putting the plugin in its own namespace and I think the code would be easier to read if it was removed.

If you agree I'd be happy to submit a PR.

**Comment by leoogh** [comment]
Hi Jamie,

Sure, no problem for a PR to change plugin’s namespace to something else. The module itself best remains at sfzero:: as more people will have code depending on it.
Originally there was no module, hence the shared namespace. I’m also in the habit of always using a namespace for any of my code so removing the namespace for the plugin is not something I would do personally. Perhaps it can be changed to sfzero_plugin:: ?

Cheers
Leo

**Comment by leoogh** [comment]
PS I enabled the issue tracker. Thanks for catching that
L

**Comment by jamiebullock** [comment]
Hi.

I've now submitted a PR with this as well as bug fix for the SFZero UI.
