### ISSUE TITLE
Change code indent to 4 spaces? 

### ISSUE THREAD

**Issue by jamiebullock** [altalogix/SFZeroModule#2]
Hi,

I'm going to change the code indent to 4 spaces on my own fork of this as I find it more readable and it's the Xcode default. I think more devs use 4 than 2. Do you want me to submit a PR for this? I know it's personal preference...

**Comment by jamiebullock** [comment]
OK, I'm closing this as I see you actually set the indentation to 2 spaces when you forked from the original stevefolta repo. It's a bit of a pity you changed the formatting and renamed member variables, because it makes merging upstream unfeasible.

**Comment by leoogh** [comment]
Yeah sorry about that. I don’t mind 4 spaces indentation btw – just that my own code base is using 2

Thanks for your efforts & hope to review your changes asap
I’ll be traveling this weekend and it’s quite hectic here overall – so may take some time
